version: "3.3"
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    networks:
      - network
      
  pgsql:
    image: postgres:12-alpine
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_db
      DIALECT: postgres
      PGDATA: /var/lib/postgresql/data/pg_data
    volumes:
     - pg_data:/var/lib/postgresql/data/pg_data
    networks:
      - network

volumes:
  pg_data:
  db:
    driver: local

networks:
  network: